# Generated by Django 5.1.1 on 2024-09-21 09:16

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_published_date'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
