# Generated by Django 5.1.1 on 2024-09-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_remove_blog_tags_blog_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
